### ISSUE TITLE
用自己生成的数据训练，效果很差

### ISSUE THREAD

**Issue by chengchaoyang** [chineseocr/chinese-ocr#118]
请教下大神，用大神提供的基础模型，训练生成的数据，大概200w张图片，效果反而更差，请教下是什么原因。我看好多人都有和我一样的疑问，博主可否公开自己用的语料库，字体库，训练方法和步骤的细节，以供大家学习参考，不胜感激。

**Comment by wenlihaoyu** [comment]
语料库是搜狗的语料，还加了一些古文诗词进去，构造的时候要把中英文混合，这样效果会好一些。字体库在ubuntu上支持中文的字体，可以去ubuntu官网上下载。训练没有什么特别的，直接训练就行。

**Comment by fuchao01** [comment]
请问使用搜狗那个1T的语料库训练吗？自己生成定长还是不定长的字体图片呢？

**Comment by wenlihaoyu** [comment]
@fuchao01 不定长和定长均可以。后面会释放不定长OCR训练代码，这样更接近真实场景，因为真实场景，定长字符相对较少。
