### ISSUE TITLE
如何在当前训练结果的基础上继续训练呢？求各位大神指点

### ISSUE THREAD

**Issue by w7851435** [chineseocr/chinese-ocr#123]
在作者提供的基础上，增加了一个手写字体的训练数据，得到结果ocr3.0.h5，而且能够识别，想要再增加一种字体，能不能在我得到的3.0的基础上继续训练呢？

**Comment by wenlihaoyu** [comment]
可以

**Comment by w7851435** [comment]
@wenlihaoyu 方便简单指点一下我该怎么操作么，非常感谢

**Comment by w7851435** [comment]
好像明白了
