### ISSUE TITLE
关于cudnn版本的问题，我安装的是 cuda-8.0+tensorflow1.3+cudnn6.0.21 ，训练的kears版本出错

### ISSUE THREAD

**Issue by frando83** [chineseocr/chinese-ocr#124]
Loaded runtime CuDNN library: 5110 (compatibility version 5100) but source was compiled with 6021 (compatibility version 6000).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.
一直报这个错，我没有安装cudnn 5110，不知道这个loaded runtime cudnn library :5110是怎么会是，我安装的是cudnn6.0.21
#define CUDNN_MAJOR      6
#define CUDNN_MINOR      0
#define CUDNN_PATCHLEVEL 21
--
#define CUDNN_VERSION    (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

**Comment by wenlihaoyu** [comment]
conda install tensorflow=1.3 tensorflow-gpu=1.3

**Comment by frando83** [comment]
谢谢，已经解决了，利用conda安装各种就可以了
