### ISSUE TITLE
ValueError: Buffer dtype mismatch, expected 'int_t' but got 'long long'

### ISSUE THREAD

**Issue by EnzoLiang** [chineseocr/chinese-ocr#125]
thanks to the author ，but I have a problem : 
 File "cython_nms.pyx", line 25, in ctpn.lib.utils.cython_nms.nms
ValueError: Buffer dtype mismatch, expected 'int_t' but got 'long long'.
I try to change "np.int_t" to "np.intp_t" in the line 25 ,but it doesnt work. Bye the way, my environment is:
windows10 ,
python3.6 ,
tensorflow1.3 ,
vs2015,keras 2.0.8, pytorch  0.3.1, tensorflow 1.3.0

**Comment by w7851435** [comment]
3.6我也遇到了这个问题，2.7对着

**Comment by EnzoLiang** [comment]
@w7851435 its cool when I change  "np.int_t" to "np.int64_t" .
