### ISSUE TITLE
invalid ELF header 

### ISSUE THREAD

**Issue by jchan698** [chineseocr/chinese-ocr#137]
你好, 在 chinese-ocr-master/ctpn/ctpn  directory里面的时候在"import model" 的阶段就显示一个
"chinese-ocr-master/ctpn/lib/utils/bbox.so: invalid ELF header"
的问题.我现在用的是Ubuntu可是下载zip包unzipped以后是用Windows然后上传到Ubuntu的系统进行模型.非常感谢所有的建议如何解决这个问题!

**Comment by wenlihaoyu** [comment]
删除 “.so”文件，重新编译，就没有问题了

**Comment by larklili** [comment]
@wenlihaoyu 删除之后继续有这样的错，怎么办呢？
ImportError: cannot import name bbox
