### ISSUE TITLE
请教关于CRNN训练的一些问题

### ISSUE THREAD

**Issue by chouxiaobei** [chineseocr/chinese-ocr#14]
你好，我看你提到的训练过程中先用2个字符来训练，再用10字符训练。请问，2个字符训练和10个字符训练过程，参数是否需要做相应修改，比如“imgW”？另外，如果一次来训练各种长度的样本，需要修改哪些地方呢，会存在什么问题吗？

**Comment by wenlihaoyu** [comment]
需要更改imgW。入股混合训练各种长度，需要修改数据迭代器函数"gen"，imgW取当前batchSize的最大imgW,不够长度的图像尽量用空白图像补成最大imgW，不要用img.resize((32,imgW))。字符数取当前batchSize的最大字符数

**Comment by chouxiaobei** [comment]
谢谢^_^
