### ISSUE TITLE
train的时候传给ctc函数的input_length里为什么有个63？

### ISSUE THREAD

**Issue by houzi09** [chineseocr/chinese-ocr#15]
请问在 train/keras-train/train.py里有个 **63** 的值，请问这个值有什么含义吗？ctc的原理有点不太明白。
`yield [X, Y, np.ones(batchSize)*int(63), np.ones(batchSize)*n_len], np.ones(batchSize)`

**Comment by houzi09** [comment]
看了下估计是 img_w // downsample_factor - 1， downsample_factor = 4。
为什么 downsample_factor 是4 呢？因为 pool_size ** 2 吗？是因为用了pool两次stride 2的降采样吧？
还有就是我看keras的ocr例子是 img_w // downsample_factor - 2 ，这-1，-2有什么区别吗？

**Comment by wenlihaoyu** [comment]
@houzi09 对的，就是这样的 。只要大于 img_w // downsample_factor - 2，其实都可以，CTC只是会多补一个black。
