### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by hongdajun** [chineseocr/chinese-ocr#150]
When I run the demo, there is a problem about this:

Demo for E:\模型\text-detection\text-detection-ctpn\data\demo\001.jpg
Traceback (most recent call last):
File "./ctpn/demo.py", line 100, in 
ctpn(sess, net, im_name)
File "./ctpn/demo.py", line 54, in ctpn
img, scale = resize_im(img, scale=TextLineCfg.SCALE, max_scale=TextLineCfg.M
AX_SCALE)
File "./ctpn/demo.py", line 17, in resize_im
f=float(scale)/min(im.shape[0], im.shape[1])
AttributeError: 'NoneType' object has no attribute 'shape'

Is anybody can help me, or teach me how to fix the error? Thanks.

**Comment by hongdajun** [comment]
E:\模型\text-detection

**Comment by wenlihaoyu** [comment]
你 输入的 img 为None，检查测试的图像是否正确
