### ISSUE TITLE
训练集数据的要求是什么？

### ISSUE THREAD

**Issue by gary-jiao** [chineseocr/chinese-ocr#155]
Hi, @wenlihaoyu ，你好，还是一个关于训练数据集的问题，之前也有人问过，但没有看到回复．
我这边生成数据集的时候，使用了以下几种字体：
１．仿宋_GB2312
２．微软vista黑体
３．楷体_GB2312
４．方正楷体GBK
５．宋体_GB18030+%26+新宋体_GB18030
然后字符集是找一些故事书生成的，大概有4500个不同的字符，然后固定生成10位长度的图片，总共生成了10000张图片．因为考虑到图片的长度最好是固定的，所以使用的字体也是一样的，这样生成的图片，和训练所需要的图片尺寸基本上一致．
按照目前能够了解的信息，生成这样的数据集应该是基本上满足要求了，训练36小时左右，ｌｏｓｓ可以降到0.008左右了，但在使用demo.py的时候，发现效果比较差，识别的错误率比在ocr目录下默认提供的h5文件还是高很多．
对了，训练是使用keras的，然后是基于train/pretrain-models/keras.hdf5开始训练的．但keys.py文件我没有改动，使用的还是你提供的那个．
能麻烦帮忙看看到底是什么原因吗？是图片数量不够？字体使用错误？keys.py里字符没有重新定义？或者是其他什么问题呢？
谢谢！

**Comment by wenlihaoyu** [comment]
训练集可能太少了。第二，你合成样本和demo.py测试的样本是否存在差距？如果只用合成的数据进行训练，测试却用的真实场景，那么估计会有一些问题。你应该加入一部分真实场景的数据。

**Comment by gary-jiao** [comment]
哦，好的，我现在重新生成了20万张图片正在训练看看效果，如果不行，再增加数量．
关于第二点，谢谢你的提示，我目前就是你说的这种方式，训练集里面没有加入真实场景数据，后面我会找一些真实场景数据再试一下．
非常感谢！
