### ISSUE TITLE
crnn识别只能用CPU？用GPU导致out of memory？

### ISSUE THREAD

**Issue by axzhcode** [chineseocr/chinese-ocr#32]
如果把crnn.py里的GPU改成True，报如下错误：
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
训练不会？

**Comment by wenlihaoyu** [comment]
可能是你的显卡内存不够吧。

**Comment by axzhcode** [comment]
@wenlihaoyu gtx1080 可用显存7.8G。。。怎么可能不够

**Comment by wenlihaoyu** [comment]
你上面就是报错： out of memory 。文本检测的时候，你如果没有限制tensorflow的GPU使用量，默认会把你GPU占用完，所以torch就没有GPU可用，自然就报错了。自己还是要多分析一下原因吧
