### ISSUE TITLE
pytorch windows  python 2.7  可以安装吗

### ISSUE THREAD

**Issue by frankzhuo** [chineseocr/chinese-ocr#43]
windows pytourch  python2.7 可以安装吗

**Comment by wenlihaoyu** [comment]
windows64 应该可以安装，不过要python3.6 conda install --offline pytorch-0.1.12-py36_0.1.12cu80.tar.bz2 详细参考这一篇文章：http://blog.csdn.net/xiangxianghehe/article/details/73500031

**Comment by frankzhuo** [comment]
我是这麽操作的不过，，遇到了AttributeError: MSVCCompiler instance has no attribute 'compiler_so'
这样的问题
