### ISSUE TITLE
请教一个关于OCR训练问题

### ISSUE THREAD

**Issue by moondaiy** [chineseocr/chinese-ocr#49]
楼主你好，请问下，我在使用你的训练好的CRNN模型进行识别的时候，感觉还是挺准确的，请问下，楼主大概用了多少数据集进行的训练，得到了目前这个model。而且能否方便透漏下，使用的硬件训练这个model花费了多少时间

**Comment by wenlihaoyu** [comment]
100多万。用普通的PC机1080显卡，训练大概一天的时间，构造训练集费了不少的时间。

**Comment by moondaiy** [comment]
谢谢啦
