### ISSUE TITLE
使用Pytorch训练问题

### ISSUE THREAD

**Issue by moondaiy** [chineseocr/chinese-ocr#58]
楼主好：
    最近一直在研究OCR相关的东西，目前在进行自己的数据集训练，使用pytorch进行 。但是在训练过程中验证代码部分，遇到个一个问题Log如下。
Start val
Traceback (most recent call last):
  File "crnn_main.py", line 258, in <module>
    testLoss,accuracy = val(crnn, test_dataset, criterion)
  File "crnn_main.py", line 165, in val
    preds = preds.squeeze(2)
RuntimeError: dimension out of range (expected to be in range of [-2, 1], but got 2)

我的环境是Anaconda3  Python2.7 没用CUDA 只是CPU版本
楼主用的python 2.7下的numpy是什么版本的。。

**Comment by wenlihaoyu** [comment]
注释掉#preds = preds.squeeze(2)

**Comment by liangping** [comment]
我最近也在关注你这个项目，但是版本问题确实比较头大，麻烦抽空写个说明，都什么用的版本。

**Comment by wenlihaoyu** [comment]
setup.sh 里面有详细的说明

**Comment by moondaiy** [comment]
谢谢回答 已经可以进行train了 有时间我在整体梳理下程序流程
