### ISSUE TITLE
run demo.py报2.7的库文件出错!!!

### ISSUE THREAD

**Issue by SubsonBigod** [chineseocr/chinese-ocr#71]
Traceback (most recent call last):
  File "/home/subson/anaconda3/envs/py27forChineseOCR/lib/python2.7/encodings/__init__.py", line 74, in search_function
    entry = _cache.get(encoding, _unknown)
AttributeError: 'NoneType' object has no attribute 'get'

```python
import codecs
from encodings import aliases
import __builtin__

_cache = {}
_unknown = '--unknown--'
_import_tail = ['*']
```

```python
def search_function(encoding):

    # Cache lookup
    entry = _cache.get(encoding, _unknown)
    if entry is not _unknown:
        return entry

```

**Comment by wenlihaoyu** [comment]
尝试重新安装encodings包，我电脑的这个文件为：
`
import codecs
from encodings import aliases
import __builtin__

_cache = {}
_unknown = '--unknown--'
_import_tail = ['*']
_norm_encoding_map = ('                                              . '
                      '0123456789       ABCDEFGHIJKLMNOPQRSTUVWXYZ     '
                      ' abcdefghijklmnopqrstuvwxyz                     '
                      '                                                '
                      '                                                '
                      '                ')
_aliases = aliases.aliases

class CodecRegistryError(LookupError, SystemError):
    pass

def normalize_encoding(encoding):

    """ Normalize an encoding name.

        Normalization works as follows: all non-alphanumeric
        characters except the dot used for Python package names are
        collapsed and replaced with a single underscore, e.g. '  -;#'
        becomes '_'. Leading and trailing underscores are removed.

        Note that encoding names should be ASCII only; if they do use
        non-ASCII characters, these must be Latin-1 compatible.

    """
    # Make sure we have an 8-bit string, because .translate() works
    # differently for Unicode strings.
    if hasattr(__builtin__, "unicode") and isinstance(encoding, unicode):
        # Note that .encode('latin-1') does *not* use the codec
        # registry, so this call doesn't recurse. (See unicodeobject.c
        # PyUnicode_AsEncodedString() for details)
        encoding = encoding.encode('latin-1')
    return '_'.join(encoding.translate(_norm_encoding_map).split())

def search_function(encoding):

    # Cache lookup
    entry = _cache.get(encoding, _unknown)
    if entry is not _unknown:
        return entry

    # Import the module:
    #
    # First try to find an alias for the normalized encoding
    # name and lookup the module using the aliased name, then try to
    # lookup the module using the standard import scheme, i.e. first
    # try in the encodings package, then at top-level.
    #
    norm_encoding = normalize_encoding(encoding)
    aliased_encoding = _aliases.get(norm_encoding) or \
                       _aliases.get(norm_encoding.replace('.', '_'))
    if aliased_encoding is not None:
        modnames = [aliased_encoding,
                    norm_encoding]
    else:
        modnames = [norm_encoding]
    for modname in modnames:
        if not modname or '.' in modname:
            continue
        try:
            # Import is absolute to prevent the possibly malicious import of a
            # module with side-effects that is not in the 'encodings' package.
            mod = __import__('encodings.' + modname, fromlist=_import_tail,
                             level=0)
        except ImportError:
            pass
        else:
            break
    else:
        mod = None

    try:
        getregentry = mod.getregentry
    except AttributeError:
        # Not a codec module
        mod = None

    if mod is None:
        # Cache misses
        _cache[encoding] = None
        return None

    # Now ask the module for the registry entry
    entry = getregentry()
    if not isinstance(entry, codecs.CodecInfo):
        if not 4 <= len(entry) <= 7:
            raise CodecRegistryError,\
                 'module "%s" (%s) failed to register' % \
                  (mod.__name__, mod.__file__)
        if not hasattr(entry[0], '__call__') or \
           not hasattr(entry[1], '__call__') or \
           (entry[2] is not None and not hasattr(entry[2], '__call__')) or \
           (entry[3] is not None and not hasattr(entry[3], '__call__')) or \
           (len(entry) > 4 and entry[4] is not None and not hasattr(entry[4], '__call__')) or \
           (len(entry) > 5 and entry[5] is not None and not hasattr(entry[5], '__call__')):
            raise CodecRegistryError,\
                'incompatible codecs in module "%s" (%s)' % \
                (mod.__name__, mod.__file__)
        if len(entry)<7 or entry[6] is None:
            entry += (None,)*(6-len(entry)) + (mod.__name__.split(".", 1)[1],)
        entry = codecs.CodecInfo(*entry)

    # Cache the codec registry entry
    _cache[encoding] = entry

    # Register its aliases (without overwriting previously registered
    # aliases)
    try:
        codecaliases = mod.getaliases()
    except AttributeError:
        pass
    else:
        for alias in codecaliases:
            if alias not in _aliases:
                _aliases[alias] = modname

    # Return the registry entry
    return entry

# Register the search_function in the Python codec registry
codecs.register(search_function)
`

**Comment by SubsonBigod** [comment]
粗略看来,该文件是一样的!第35行定义为dict,第74行使用其get方法,按理来说正常的.
```python
import codecs
from encodings import aliases
import __builtin__

_cache = {}
_unknown = '--unknown--'
_import_tail = ['*']
_norm_encoding_map = ('                                              . '
                      '0123456789       ABCDEFGHIJKLMNOPQRSTUVWXYZ     '
                      ' abcdefghijklmnopqrstuvwxyz                     '
                      '                                                '
                      '                                                '
                      '                ')
_aliases = aliases.aliases

class CodecRegistryError(LookupError, SystemError):
    pass

def normalize_encoding(encoding):

    """ Normalize an encoding name.

        Normalization works as follows: all non-alphanumeric
        characters except the dot used for Python package names are
        collapsed and replaced with a single underscore, e.g. '  -;#'
        becomes '_'. Leading and trailing underscores are removed.

        Note that encoding names should be ASCII only; if they do use
        non-ASCII characters, these must be Latin-1 compatible.

    """
    # Make sure we have an 8-bit string, because .translate() works
    # differently for Unicode strings.
    if hasattr(__builtin__, "unicode") and isinstance(encoding, unicode):
        # Note that .encode('latin-1') does *not* use the codec
        # registry, so this call doesn't recurse. (See unicodeobject.c
        # PyUnicode_AsEncodedString() for details)
        encoding = encoding.encode('latin-1')
    return '_'.join(encoding.translate(_norm_encoding_map).split())

def search_function(encoding):

    # Cache lookup
    entry = _cache.get(encoding, _unknown)
    if entry is not _unknown:
        return entry

    # Import the module:
    #
    # First try to find an alias for the normalized encoding
    # name and lookup the module using the aliased name, then try to
    # lookup the module using the standard import scheme, i.e. first
    # try in the encodings package, then at top-level.
    #
    norm_encoding = normalize_encoding(encoding)
    aliased_encoding = _aliases.get(norm_encoding) or \
                       _aliases.get(norm_encoding.replace('.', '_'))
    if aliased_encoding is not None:
        modnames = [aliased_encoding,
                    norm_encoding]
    else:
        modnames = [norm_encoding]
    for modname in modnames:
        if not modname or '.' in modname:
            continue
        try:
            # Import is absolute to prevent the possibly malicious import of a
            # module with side-effects that is not in the 'encodings' package.
            mod = __import__('encodings.' + modname, fromlist=_import_tail,
                             level=0)
        except ImportError:
            pass
        else:
            break
    else:
        mod = None

    try:
        getregentry = mod.getregentry
    except AttributeError:
        # Not a codec module
        mod = None

    if mod is None:
        # Cache misses
        _cache[encoding] = None
        return None

    # Now ask the module for the registry entry
    entry = getregentry()
    if not isinstance(entry, codecs.CodecInfo):
        if not 4 <= len(entry) <= 7:
            raise CodecRegistryError,\
                 'module "%s" (%s) failed to register' % \
                  (mod.__name__, mod.__file__)
        if not hasattr(entry[0], '__call__') or \
           not hasattr(entry[1], '__call__') or \
           (entry[2] is not None and not hasattr(entry[2], '__call__')) or \
           (entry[3] is not None and not hasattr(entry[3], '__call__')) or \
           (len(entry) > 4 and entry[4] is not None and not hasattr(entry[4], '__call__')) or \
           (len(entry) > 5 and entry[5] is not None and not hasattr(entry[5], '__call__')):
            raise CodecRegistryError,\
                'incompatible codecs in module "%s" (%s)' % \
                (mod.__name__, mod.__file__)
        if len(entry)<7 or entry[6] is None:
            entry += (None,)*(6-len(entry)) + (mod.__name__.split(".", 1)[1],)
        entry = codecs.CodecInfo(*entry)

    # Cache the codec registry entry
    _cache[encoding] = entry

    # Register its aliases (without overwriting previously registered
    # aliases)
    try:
        codecaliases = mod.getaliases()
    except AttributeError:
        pass
    else:
        for alias in codecaliases:
            if alias not in _aliases:
                _aliases[alias] = modname

    # Return the registry entry
    return entry

# Register the search_function in the Python codec registry
codecs.register(search_function)
```

**Comment by SubsonBigod** [comment]
将你给出的文件与我给出的文件,进行了diff比较,证明两者是完全相同的.
另外,重建安装构建一遍依然发生同样问题.
请问,作者有没有可能使用了同"_cache"命名的全局变量?我也查找过,没找到.
有没有可能是其它包的同名变量产生的干扰?
附上我使用的包:
```
backports-abc (0.5)
backports.functools-lru-cache (1.4)
backports.shutil-get-terminal-size (1.0.0)
backports.ssl-match-hostname (3.5.0.1)
bleach (2.1.2)
certifi (2017.11.5)
cffi (1.11.4)
configparser (3.5.0)
cycler (0.10.0)
Cython (0.27.3)
decorator (4.2.1)
easydict (1.7)
entrypoints (0.2.3)
enum34 (1.1.6)
functools32 (3.2.3.post2)
h5py (2.7.1)
html5lib (1.0.1)
ipykernel (4.7.0)
ipython (5.4.1)
ipython-genutils (0.2.0)
ipywidgets (7.1.0)
Jinja2 (2.10)
jsonschema (2.6.0)
jupyter-client (5.2.1)
jupyter-console (5.2.0)
jupyter-core (4.4.0)
Keras (2.0.8)
lmdb (0.93)
mahotas (1.4.4)
MarkupSafe (1.0)
matplotlib (2.1.2)
mistune (0.8.3)
nbconvert (5.3.1)
nbformat (4.4.0)
notebook (5.3.1)
numpy (1.14.0)
opencv-python (3.4.0.12)
pandocfilters (1.4.2)
pathlib2 (2.3.0)
pexpect (4.3.1)
pickleshare (0.7.4)
PIL (1.1.7)
Pillow (5.0.0)
pip (9.0.1)
prompt-toolkit (1.0.15)
ptyprocess (0.5.2)
pycparser (2.18)
Pygments (2.2.0)
pyparsing (2.2.0)
python-dateutil (2.6.1)
pytz (2017.3)
PyYAML (3.12)
pyzmq (16.0.3)
qtconsole (4.3.1)
scandir (1.6)
scipy (1.0.0)
Send2Trash (1.4.2)
setuptools (38.4.0)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.11.0)
subprocess32 (3.2.7)
terminado (0.8.1)
testpath (0.3.1)
torch (0.1.12.post2)
torchvision (0.1.8)
tornado (4.5.3)
traitlets (4.3.2)
wcwidth (0.1.7)
webencodings (0.5.1)
wheel (0.30.0)
widgetsnbextension (3.1.0)
```

**Comment by SubsonBigod** [comment]
将你给出的文件与我给出的文件,进行了diff比较,证明两者是完全相同的.
另外,重建安装构建一遍依然发生同样问题.
请问,作者有没有可能使用了同"_cache"命名的全局变量?我也查找过,没找到.
但是,通过下面方法发现存在同名全局变量
在encondings包的__init__.py文件的search_function方法的75行之前加上如下代码
```python
    if "_cache" in locals().keys():
        print "in locals.keys"
    else:
        print "not in locals.keys"

    if "_cache" in globals().keys():
        print "in globals.keys"
    else:
        print "not in globals.keys"
    
    print _cache
    print type(_cache)
```
输出:
```
not in locals.keys
in globals.keys
None
<type 'NoneType'>
```
鉴于此,有没有可能是其它包的同名全局变量产生干扰?
下面附上我使用的包:
```
backports-abc (0.5)
backports.functools-lru-cache (1.4)
backports.shutil-get-terminal-size (1.0.0)
backports.ssl-match-hostname (3.5.0.1)
bleach (2.1.2)
certifi (2017.11.5)
cffi (1.11.4)
configparser (3.5.0)
cycler (0.10.0)
Cython (0.27.3)
decorator (4.2.1)
easydict (1.7)
entrypoints (0.2.3)
enum34 (1.1.6)
functools32 (3.2.3.post2)
h5py (2.7.1)
html5lib (1.0.1)
ipykernel (4.7.0)
ipython (5.4.1)
ipython-genutils (0.2.0)
ipywidgets (7.1.0)
Jinja2 (2.10)
jsonschema (2.6.0)
jupyter-client (5.2.1)
jupyter-console (5.2.0)
jupyter-core (4.4.0)
Keras (2.0.8)
lmdb (0.93)
mahotas (1.4.4)
MarkupSafe (1.0)
matplotlib (2.1.2)
mistune (0.8.3)
nbconvert (5.3.1)
nbformat (4.4.0)
notebook (5.3.1)
numpy (1.14.0)
opencv-python (3.4.0.12)
pandocfilters (1.4.2)
pathlib2 (2.3.0)
pexpect (4.3.1)
pickleshare (0.7.4)
PIL (1.1.7)
Pillow (5.0.0)
pip (9.0.1)
prompt-toolkit (1.0.15)
ptyprocess (0.5.2)
pycparser (2.18)
Pygments (2.2.0)
pyparsing (2.2.0)
python-dateutil (2.6.1)
pytz (2017.3)
PyYAML (3.12)
pyzmq (16.0.3)
qtconsole (4.3.1)
scandir (1.6)
scipy (1.0.0)
Send2Trash (1.4.2)
setuptools (38.4.0)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.11.0)
subprocess32 (3.2.7)
terminado (0.8.1)
testpath (0.3.1)
torch (0.1.12.post2)
torchvision (0.1.8)
tornado (4.5.3)
traitlets (4.3.2)
wcwidth (0.1.7)
webencodings (0.5.1)
wheel (0.30.0)
widgetsnbextension (3.1.0)
```

**Comment by wenlihaoyu** [comment]
重新建一个python环境试一下吧

**Comment by YibanYiban** [comment]
matplotlib
