### ISSUE TITLE
关于字体的问题

### ISSUE THREAD

**Issue by huang-aoyun** [chineseocr/chinese-ocr#72]
您好。
1、我用您的pytorch迁移的时候，log文件夹里同时也出现了10中字体文件，请问这是训练用的字体吗？如果是，怎样添加其他字体？
2、目前有没有尝试一些调参，因为在测试的时候，较为复杂的背景识别效果较低？

**Comment by wenlihaoyu** [comment]
模型训练不需要字体，构造训练集才需要
