### ISSUE TITLE
使用新训练的结果去识别图片出错

### ISSUE THREAD

**Issue by w7851435** [chineseocr/chinese-ocr#73]
错误提示：ValueError: You are trying to load a weight file containing 13 layers into a model with 16 layers.
训练内容：图片验证码和对应的结果

训练时修改图片大小为验证码的大小会出现如下错误：
ValueError: Negative dimension size caused by subtracting 2 from 1 for 'conv7/convolution' (op: 'Conv2D') with input shapes: [?,1,?,512], [2,2,512,512].
使用代码中默认大小不会出错，但是使用训练结果时出现开始说的错误

望大神能指点一二

**Comment by wenlihaoyu** [comment]
什么地方？

**Comment by w7851435** [comment]
使用自己准备的数据进行训练，训练时修改keras-train/train.py 中的imgH和imgW为实际训练图片的大小，会显示错误
`ValueError: Negative dimension size caused by subtracting 2 from 1 for 'conv7/convolution' (op: 'Conv2D') with input shapes: [?,1,?,512], [2,2,512,512].`
直接使用256*32的图片进行训练，训练成果以后，拷贝训练结果到angle文件中，修改对应文件名，执行demo.py，报错如下：
`ValueError: You are trying to load a weight file containing 13 layers into a model with 16 layers.`

**Comment by w7851435** [comment]
执行demo.py成功后
本地生成了1000张图片进行训练大小256*32，内容是随机的一些常见的汉字，格式为jpg和对应内容的txt,放到了 train/data/dataline目录下面（1.jpg  1.txt。。。。。）
执行keras-train/trainbatch.py结束，没有报错
将save_model目录下生成的model.****.h5拷贝到angle目录，修改名字为modelAngle.h5，执行demo.py，显示错误ValueError: You are trying to load a weight file containing 13 layers into a model with 16 layers.

**Comment by wenlihaoyu** [comment]
@w7851435 你搞错了吧，angle目录是训练文本方向检测的模型。

**Comment by w7851435** [comment]
搞定了，非常感谢
