### ISSUE TITLE
关于误检（是否文字行）false positive的问题

### ISSUE THREAD

**Issue by dajiangxiaoyan** [chineseocr/chinese-ocr#74]
Hi,  all

大家在做文本检测的时候，对于非文字行检测成文字行的text line是如何处理的？
例如下面图片，上面2个文本框：
![image](https://user-images.githubusercontent.com/17979833/35265994-ccecaea6-005c-11e8-992a-3af00a3637d6.png)

一开始我的想法是在检测和识别中间加一个分类模型，用来区分文本行。但是负样本的空间实在太大，常用的分类的模型只能过滤部分，效果有限。另外分类模型作用在每个问本行上，一张图片预测的时间大大增加。

大家有什么好的想法吗？

**Comment by w7851435** [comment]
我觉得这种可以在识别出结果以后再使用算法对文本进行 语法，语意的修正

**Comment by dajiangxiaoyan** [comment]
@w7851435  这样就和语言相关了，你有试过其他的，比如cptn之后，加分类模型吗？

**Comment by wenlihaoyu** [comment]
不用那么复杂，调ctpn的参数就行，TEXT_PROPOSALS_MIN_SCORE 和LINE_MIN_SCORE

**Comment by dajiangxiaoyan** [comment]
@wenlihaoyu  我尝试过各种概率的组合。总是有 非字误检的， 如果把概率提到特别高，有很多小的字就检出不来了。
