### ISSUE TITLE
关于pytorch训练的问题

### ISSUE THREAD

**Issue by chengchaoyang** [chineseocr/chinese-ocr#76]
1.训练时不加--cuda参数，可以用cpu正常训练，但是有启动GPU ，占了一小部分显存。计算时在cpu进行。2.训练时加上--cuda参数，训练在计算trainbatch的CTCLoss时就自动中断，没有任何报错信息。程序退出以后，程序还在占用gpu显存，而且4个进程还在后台挂着。不知道是什么原因？

**Comment by wenlihaoyu** [comment]
pytorch训练的时候，默认用了4个进程去加载训练数据。

**Comment by ChanChiChoi** [comment]
前面加 CUDA_VISIBLE_DEVICES='' python crnn_main.py  这样，直接让显卡不可见，然后用cpu模式
