### ISSUE TITLE
运行sh make.sh的时候出错，环境是cuda-8.0,cudnn 7 和cudnn 6都尝试了

### ISSUE THREAD

**Issue by LJ147** [chineseocr/chinese-ocr#82]
你好，我的环境是cuda-8.0,cudnn 7 和cudnn 6都尝试了，报错信息如下，请问这是哪个环节出错了呢？

sh make.sh 之前的命令都执行成功了

sh make.sh
running build_ext
skipping 'bbox.c' Cython extension (up-to-date)
building 'utils.bbox' extension
creating build
creating build/temp.linux-x86_64-2.7
{'gcc': ['-Wno-cpp', '-Wno-unused-function']}
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/anaconda3/envs/chinese-ocr/lib/python2.7/site-packages/numpy/core/include -I/root/anaconda3/envs/chinese-ocr/include/python2.7 -c bbox.c -o build/temp.linux-x86_64-2.7/bbox.o -Wno-cpp -Wno-unused-function
creating /root/disk/code/chinese-ocr/ctpn/lib/utils/utils
gcc -pthread -shared -L/root/anaconda3/envs/chinese-ocr/lib -Wl,-rpath=/root/anaconda3/envs/chinese-ocr/lib,--no-as-needed build/temp.linux-x86_64-2.7/bbox.o -L/root/anaconda3/envs/chinese-ocr/lib -lpython2.7 -o /root/disk/code/chinese-ocr/ctpn/lib/utils/utils/bbox.so
skipping 'cython_nms.c' Cython extension (up-to-date)
building 'utils.cython_nms' extension
{'gcc': ['-Wno-cpp', '-Wno-unused-function']}
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/anaconda3/envs/chinese-ocr/lib/python2.7/site-packages/numpy/core/include -I/root/anaconda3/envs/chinese-ocr/include/python2.7 -c cython_nms.c -o build/temp.linux-x86_64-2.7/cython_nms.o -Wno-cpp -Wno-unused-function
gcc -pthread -shared -L/root/anaconda3/envs/chinese-ocr/lib -Wl,-rpath=/root/anaconda3/envs/chinese-ocr/lib,--no-as-needed build/temp.linux-x86_64-2.7/cython_nms.o -L/root/anaconda3/envs/chinese-ocr/lib -lpython2.7 -o /root/disk/code/chinese-ocr/ctpn/lib/utils/utils/cython_nms.so
skipping 'gpu_nms.cpp' Cython extension (up-to-date)
building 'utils.gpu_nms' extension
{'gcc': ['-Wno-unused-function'], 'nvcc': ['-arch=sm_61', '--ptxas-options=-v', '-c', '--compiler-options', "'-fPIC'"]}
/usr/local/cuda/bin/nvcc -I/root/anaconda3/envs/chinese-ocr/lib/python2.7/site-packages/numpy/core/include -I/usr/local/cuda/include -I/root/anaconda3/envs/chinese-ocr/include/python2.7 -c nms_kernel.cu -o build/temp.linux-x86_64-2.7/nms_kernel.o -arch=sm_61 --ptxas-options=-v -c --compiler-options '-fPIC'
ptxas info    : 0 bytes gmem
ptxas info    : Compiling entry function '_Z10nms_kernelifPKfPy' for 'sm_61'
ptxas info    : Function properties for _Z10nms_kernelifPKfPy
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 22 registers, 1280 bytes smem, 344 bytes cmem[0], 12 bytes cmem[2]
{'gcc': ['-Wno-unused-function'], 'nvcc': ['-arch=sm_61', '--ptxas-options=-v', '-c', '--compiler-options', "'-fPIC'"]}
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/anaconda3/envs/chinese-ocr/lib/python2.7/site-packages/numpy/core/include -I/usr/local/cuda/include -I/root/anaconda3/envs/chinese-ocr/include/python2.7 -c gpu_nms.cpp -o build/temp.linux-x86_64-2.7/gpu_nms.o -Wno-unused-function
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from /root/anaconda3/envs/chinese-ocr/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1809:0,
                 from /root/anaconda3/envs/chinese-ocr/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /root/anaconda3/envs/chinese-ocr/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from gpu_nms.cpp:283:
/root/anaconda3/envs/chinese-ocr/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
g++ -pthread -shared -L/root/anaconda3/envs/chinese-ocr/lib -Wl,-rpath=/root/anaconda3/envs/chinese-ocr/lib,--no-as-needed build/temp.linux-x86_64-2.7/nms_kernel.o build/temp.linux-x86_64-2.7/gpu_nms.o -L/usr/local/cuda/lib64 -L/root/anaconda3/envs/chinese-ocr/lib -Wl,-R/usr/local/cuda/lib64 -lcudart -lpython2.7 -o /root/disk/code/chinese-ocr/ctpn/lib/utils/utils/gpu_nms.so

**Comment by wenlihaoyu** [comment]
这不是报错吧，只是警告信息

**Comment by LJ147** [comment]
是警告信号啊，但是到这里就停止了，后面的指令都没有执行啊

全部的指令是：

cython bbox.pyx
cython cython_nms.pyx
cython gpu_nms.pyx
python setup.py build_ext --inplace
mv utils/* ./
rm -rf build
rm -rf utils


应该是执行到python setup.py build_ext --inplace
这里的时候就退出了，也没看到具体的报错
