### ISSUE TITLE
现有数据如何再新增繁体字进去？

### ISSUE THREAD

**Issue by tomtao** [chineseocr/chinese-ocr#85]
现有数据如何再新增繁体字进去？

**Comment by hustbobo** [comment]
字典里面要新加，模型的最后输出要改变

**Comment by tomtao** [comment]
@hustbobo 字典是要加繁體字進去嗎？模型輸出要改什麼？最後也是要重新訓練嗎

**Comment by hustbobo** [comment]
@tomtao 重新训练是最简单，准备新的训练集，包含繁体字，把这些繁体字也加到你的字典里面去，就是那个key文件，训练和识别的时候都需要修改key.py

**Comment by tomtao** [comment]
@hustbobo  新的训练集是指1.jpg,1.txt这样的吗，然后简体繁体都要有吗？另外，不同字体产生的jpg的大小会不一样，好像训练不了？

**Comment by wenlihaoyu** [comment]
修改base_model模型的输出层，再训练即可。
