### ISSUE TITLE
为何指定特定GPU无效

### ISSUE THREAD

**Issue by YouyiWei** [chineseocr/chinese-ocr#91]
你好，感谢分享，请问为什么我用“os.environ["CUDA_VISIBLE_DEVICES"]=”的方式无法指定GPU，还是会占满所有的卡，你有考虑过这种问题吗，谢谢！

**Comment by wenlihaoyu** [comment]
import os
import tensorflow as tf
import keras.backend.tensorflow_backend as KTF

# 指定第一块GPU可用 
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

config = tf.ConfigProto()  
config.gpu_options.allow_growth=True   #不全部占满显存, 按需分配
sess = tf.Session(config=config)

KTF.set_session(sess)

**Comment by YouyiWei** [comment]
已经解决了，谢谢 : )
